server:
  servlet:
    session:
      cookie:
        path: / # 적용될 URL 경로를 나타냅니다.
        name: SESSION # 이름을 지정합니다.

spring:
  session:
    redis:
      repository-type: indexed
      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
  data:
    redis:
      host: localhost
      port: 6383
